### PR TITLE
replace path.join to path.resolve, ref #68

### LINKED ISSUE #68: 403 Error on login page when refreshed
### Reproduction Steps
1. Go to https://todo.leopolicastro.com/login - make sure you are not refreshed
2. Click refresh

### Expected
 - Login page should reload

### Expected
 - Get a 403 Unauthorized

image

### PR DESCRIPTION
**Pull request by ErnieAtLYD**
Attempt to try to resolve #68

### CODE REVIEW

File: server/app.js [hunk 1]
```diff
@@ -21,10 +21,9 @@ app.use('/api/users', openRoutes);
 
 app.use(cookieParser());
 
-//
 if (process.env.NODE_ENV === 'production') {
   // Serve any static files
-  app.use(express.static(path.join(__dirname, '../client/build')));
+  app.use(express.static(path.resolve(__dirname, '..', 'client', 'build')));
```
Comment (wkennedy8) [inline server/app.js:26]: each path needs to be a string?

**Review by cececlar — APPROVED** [review]

File: server/app.js (hunk 1 above)
Comment (ErnieAtLYD) [reply server/app.js:26]: @wkennedy8 so yeah, that's one way to do it. The idea is that it concantates all the arguments to become an absolute path.
